### ISSUE TITLE
Repos for .debs

### ISSUE THREAD

**Issue by tbelway** [ABotelho23/LinuxSetup#2]
Skype
https://go.skype.com/skypeforlinux-64.deb

Discord
https://discordapp.com/api/download?platform=linux&format=deb

Google Play Music
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/download/v4.5.0/google-play-music-desktop-player_4.5.0_amd64.deb

Teamviewer
https://download.teamviewer.com/download/linux/teamviewer_amd64.deb

Insync
https://d2t3ff60b2tol4.cloudfront.net/builds/insync_1.4.5.37069-artful_amd64.deb

**Comment by ABotelho23** [comment]
output_document = file
Set the output filename—the same as ‘-O file’.

for reference: https://www.gnu.org/software/wget/manual/wget.html#Download-Options

**Comment by ABotelho23** [comment]
c5f38167099d01aa5beafc1e3433ffd417c868a5
