### ISSUE TITLE
Plank themes

### ISSUE THREAD

**Issue by tbelway** [ABotelho23/LinuxSetup#3]
git clone https://github.com/LinxGem33/Plank-Themes
sudo cp -r ./Plank-Themes/'Plank Themes'/* /usr/share/plank/themes

**Comment by tbelway** [comment]
https://github.com/erikdubois/plankthemes
YOU WILL FIGURE IT OUT

**Comment by ABotelho23** [comment]
5f748ea71deda326dc884f2610a109ed8b9e2f61
